# This is a basic workflow to help you get started with Actions

name: Build Binary

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the v20.10.10 branch
  push:
    branches: [ v20.10.10 ]
  pull_request:
    branches: [ v20.10.10 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: make binary
      run: make binary
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: bundles-${{ github.run_id }}
        path: bundles/*
